pipeline:
  identifier: Build_lithesheeli1_maven_project_1718807153329
  name: Build maven-project
  orgIdentifier: default
  projectIdentifier: First_Project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: lithesheeli1/maven-project
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
